CREATE TABLE Bids (
    UID      INT NOT NULL,
    PID      INT NOT NULL,
    BidPrice INT NOT NULL,
    PRIMARY KEY CLUSTERED (UID ASC, PID ASC),
    CONSTRAINT FK_Bids_ToTable FOREIGN KEY (UID) REFERENCES User (UID),
    CONSTRAINT FK_Bids_ToTable_1 FOREIGN KEY (PID) REFERENCES Property (PID)
);

